$(document).ready(function () {
  $("#home").click(function () {
    $(".homeContent").show();
    $(".challengeContent").hide();
    $(".changeContent").hide();
    $(".contentReasons").hide();
    $("contentImpact").hide();
    $(".teamcontent").hide();
    $(".contactContent").hide();
    $(".contfooter").show();
    $("#home").css({ color: "#f87c24" });
    $("#challenge").css({ color: "black" });
    $("#change").css({ color: "black" });
    $("#impact").css({ color: "black" });
    $("#upili").css({ color: "black" });
    $("#reason").css({ color: "black" });
    $("#team").css({ color: "black" });
    $("#blog").css({ color: "black" });
    $("#donate").css({ color: "black" });
    $("#contact").css({ color: "black" });
  });
  $("#challenge").click(function () {
    $(".homeContent").hide();
    $(".challengeContent").show();
    $(".changeContent").hide();
    $(".contentReasons").hide();
    $("contentImpact").hide();
    $(".teamcontent").hide();
    $(".contactContent").hide();
    $(".contfooter").show();
    $("#home").css({ color: "black" });
    $("#challenge").css({ color: "#f87c24" });
    $("#change").css({ color: "black" });
    $("#impact").css({ color: "black" });
    $("#upili").css({ color: "black" });
    $("#reason").css({ color: "black" });
    $("#team").css({ color: "black" });
    $("#blog").css({ color: "black" });
    $("#donate").css({ color: "black" });
    $("#contact").css({ color: "black" });
  });
  $("#change").click(function () {
    $(".homeContent").hide();
    $(".challengeContent").hide();
    $(".changeContent").show();
    $(".contentReasons").hide();
    $("contentImpact").hide();
    $(".teamcontent").hide();
    $(".contactContent").hide();
    $(".contfooter").show();
    $("#home").css({ color: "black" });
    $("#challenge").css({ color: "black" });
    $("#change").css({ color: "#f87c24" });
    $("#impact").css({ color: "black" });
    $("#upili").css({ color: "black" });
    $("#reason").css({ color: "black" });
    $("#team").css({ color: "black" });
    $("#blog").css({ color: "black" });
    $("#donate").css({ color: "black" });
    $("#contact").css({ color: "black" });
  });
  $("#impact").click(function () {
    $(".homeContent").hide();
    $(".challengeContent").hide();
    $(".changeContent").hide();
    $("contentImpact").show();
    $(".contentReasons").hide();
    $(".teamcontent").hide();
    $(".contactContent").hide();
    $(".contfooter").show();
    $("#home").css({ color: "black" });
    $("#challenge").css({ color: "#black" });
    $("#change").css({ color: "black" });
    $("#impact").css({ color: "#f87c24" });
    $("#upili").css({ color: "black" });
    $("#reason").css({ color: "black" });
    $("#team").css({ color: "black" });
    $("#blog").css({ color: "black" });
    $("#donate").css({ color: "black" });
    $("#contact").css({ color: "black" });
  });
  $("#reason").click(function () {
    $(".homeContent").hide();
    $(".challengeContent").hide();
    $(".changeContent").hide();
    $("contentImpact").hide();
    $(".contentReasons").show();
    $(".teamcontent").hide();
    $(".contactContent").hide();
    $(".contfooter").show();
    $("#home").css({ color: "black" });
    $("#challenge").css({ color: "#black" });
    $("#change").css({ color: "#black" });
    $("#impact").css({ color: "black" });
    $("#upili").css({ color: "black" });
    $("#reason").css({ color: "#f87c24" });
    $("#team").css({ color: "black" });
    $("#blog").css({ color: "black" });
    $("#donate").css({ color: "black" });
    $("#contact").css({ color: "black" });
  });
  $("#upili").click(function () {
    $(".homeContent").hide();
    $(".challengeContent").hide();
    $(".changeContent").hide();
    $("contentImpact").show();
    $(".contentReasons").hide();
    $(".teamcontent").hide();
    $(".contactContent").hide();
    $(".contfooter").show();
    $("#home").css({ color: "black" });
    $("#challenge").css({ color: "black" });
    $("#change").css({ color: "black" });
    $("#impact").css({ color: "black" });
    $("#upili").css({ color: "#f87c24" });
    $("#reason").css({ color: "black" });
    $("#team").css({ color: "black" });
    $("#blog").css({ color: "black" });
    $("#donate").css({ color: "black" });
    $("#contact").css({ color: "black" });
  });
  $("#team").click(function () {
    $(".homeContent").hide();
    $(".challengeContent").hide();
    $(".changeContent").hide();
    $("contentImpact").hide();
    $(".contentReasons").hide();
    $(".teamcontent").show();
    $(".contactContent").hide();
    $(".contfooter").show();
    $("#home").css({ color: "black" });
    $("#challenge").css({ color: "black" });
    $("#change").css({ color: "black" });
    $("#impact").css({ color: "black" });
    $("#upili").css({ color: "black" });
    $("#reason").css({ color: "black" });
    $("#team").css({ color: "#f87c24" });
    $("#blog").css({ color: "black" });
    $("#donate").css({ color: "black" });
    $("#contact").css({ color: "black" });
  });
  $("#contact").click(function () {
    $(".homeContent").hide();
    $(".challengeContent").hide();uuy78jizmkjy
    $(".changeContent").hide();
    $("contentImpact").hide();
    $(".contentReasons").hide();
    $(".teamcontent").hide();
    $(".contactContent").show();
    $(".contfooter").show();
    $("#home").css({ color: "black" });
    $("#challenge").css({ color: "#black" });
    $("#change").css({ color: "black" });
    $("#impact").css({ color: "black" });
    $("#upili").css({ color: "black" });
    $("#reason").css({ color: "black" });
    $("#team").css({ color: "black" });
    $("#blog").css({ color: "black" });
    $("#donate").css({ color: "black" });
    $("#contact").css({ color: "#f87c24" });
  });
});
